In [1]:
import pandas as pd
from openpyxl import load_workbook

In [2]:
files = !dir /b
files

['.ipynb_checkpoints',
 'Child poverty data.ipynb',
 'local_child_poverty_basket_of_indicators.xlsx']

In [3]:
wb = load_workbook("local_child_poverty_basket_of_indicators.xlsx")

Show a D3/carto map of the uk with the different boundaries drawn in and coloured based on the 'badness' of infant mortality/life expectancy(m/f). We can then show which other country is most similar to that particular place. When the user clicks on the boundary area, the Plotly charts change to show a scatterplot matrix of that variable against all the explanatory variables with that boundary's data point highlighted.

We can then show time series charts of the explanatory variables, grouping as such: (Employment rate, 'Employment rate (male)', 'Employment rate (female)'), (obese_reception, underweight_reception), then singles.

Potential explanatory variables:
- %of children in workless households
- low income families
- overall employment rate
- average earnings pw
- affordable housing
- obese reception
- underweight reception

Response variables:
- infant_mortality
- life expectancy
- FSMgap at KS4


UK boundary data: http://statistics.data.gov.uk/doc/statistical-geography/E06000001

In [4]:
explanatoryVariables = ['Workless households_children', 
                        'Employment rate',
                        'Employment rate (male)',
                        'Employment rate (female)',
                       'average_earnings',
                       'FSM GAP KS4',
                       'Affordable_housing',
                         'obese_reception',
                         'underweight_reception',
                        'Young offenders',
                       'Low Birth Weight',]

responseVariables = ['Life expectancy_m',
                     'Life expectancy_f',
                    'Infant_mortality',]

In [11]:
explan = {}
for var in explanatoryVariables:
    explan[var] = pd.read_excel("local_child_poverty_basket_of_indicators.xlsx", sheetname = var, skiprows=3)

In [12]:
response = {}
for var in responseVariables:
    response[var] = pd.read_excel("local_child_poverty_basket_of_indicators.xlsx", sheetname = var, skiprows=3)

In [13]:
explan.keys()

dict_keys(['Affordable_housing', 'Employment rate (male)', 'Workless households_children', 'average_earnings', 'FSM GAP KS4', 'obese_reception', 'underweight_reception', 'Employment rate (female)', 'Employment rate'])

In [16]:
explan['Workless households_children']

,Boundary ID,Old Boundary ID,Boundary Name,Latest Data,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,E06000001,00EB,Hartlepool,0.25,0.22,0.18,0.17,0.2,0.2,0.24,0.26,0.31,0.29,0.25
1,E06000002,00EC,Middlesbrough,0.22,0.23,0.2,0.24,0.21,0.25,0.23,0.3,0.32,0.3,0.22
2,E06000003,00EE,Redcar and Cleveland,0.2,0.2,0.17,0.19,0.19,0.2,0.2,0.21,0.23,0.2,0.2
3,E06000004,00EF,Stockton-on-Tees,0.17,0.19,0.18,0.17,0.16,0.17,0.16,0.17,0.17,0.18,0.17
4,E06000005,00EH,Darlington,0.14,0.16,0.14,0.17,0.17,0.15,0.17,0.21,0.22,0.21,0.14
5,E06000006,00ET,Halton,0.17,0.25,0.18,0.22,0.23,0.27,0.29,0.16,0.22,0.2,0.17
6,E06000007,00EU,Warrington,0.09,0.08,0.08,0.07,0.08,0.1,0.18,0.12,0.11,0.13,0.09
7,E06000008,00EX,Blackburn with Darwen,0.17,0.17,0.22,0.22,0.2,0.19,0.17,0.2,0.2,0.24,0.17
8,E06000009,00EY,Blackpool,0.24,0.2,0.22,0.26,0.32,0.29,0.28,0.21,0.24,0.2,0.24
9,E06000010,00FA,"Kingston upon Hull, City of",0.24,0.24,0.23,0.32,0.29,0.29,0.24,0.31,0.29,0.24,0.24
10,E06000011,00FB,East Riding of Yorkshire,0.08,0.11,0.08,0.09,0.08,0.09,0.07,0.08,0.06,0.07,0.08
11,E06000012,00FC,North East Lincolnshire,0.21,0.18,0.22,0.24,0.23,0.2,0.23,0.23,0.26,0.26,0.21
12,E06000013,00FD,North Lincolnshire,0.13,0.12,0.14,0.15,0.15,0.16,0.16,0.16,0.2,0.23,0.13
13,E06000014,00FF,York,0.08,0.1,0.09,0.07,0.08,0.07,0.1,0.1,0.1,0.06,0.08
14,E06000015,00FK,Derby,0.16,0.21,0.23,0.17,0.16,0.18,0.21,0.19,0.19,0.19,0.16
15,E06000016,00FN,Leicester,0.2,0.28,0.29,0.26,0.24,0.31,0.26,0.29,0.27,0.2,0.2
16,E06000017,00FP,Rutland,-,0.05,0.03,0.04,0.11,0.07,0.12,0.08,0.03,0.02,-
17,E06000018,00FY,Nottingham,0.27,0.26,0.27,0.26,0.27,0.24,0.3,0.32,0.31,0.25,0.27
18,E06000019,00GA,"Herefordshire, County of",0.1,0.1,0.09,0.08,0.06,0.11,0.1,0.14,0.11,0.07,0.1
19,E06000020,00GF,Telford and Wrekin,0.21,0.18,0.16,0.19,0.15,0.16,0.21,0.22,0.22,0.19,0.21
20,E06000021,00GL,Stoke-on-Trent,0.21,0.17,0.23,0.22,0.23,0.22,0.26,0.24,0.22,0.22,0.21
21,E06000022,00HA,Bath and North East Somerset,0.07,0.14,0.09,0.13,0.1,0.08,0.18,0.12,0.09,0.12,0.07
22,E06000023,00HB,"Bristol, City of",0.17,0.19,0.16,0.17,0.2,0.21,0.22,0.15,0.17,0.19,0.17
23,E06000024,00HC,North Somerset,0.08,0.11,0.07,0.08,0.07,0.11,0.08,0.13,0.07,0.09,0.08
24,E06000025,00HD,South Gloucestershire,0.12,0.08,0.07,0.06,0.07,0.09,0.12,0.07,0.06,0.07,0.12
25,E06000026,00HG,Plymouth,0.16,0.17,0.16,0.18,0.12,0.15,0.2,0.15,0.15,0.21,0.16
26,E06000027,00HH,Torbay,0.1,0.14,0.14,0.14,0.13,0.16,0.19,0.2,0.19,0.14,0.1
27,E06000028,00HN,Bournemouth,0.13,0.16,0.11,0.12,0.14,0.16,0.17,0.19,0.14,0.15,0.13
28,E06000029,00HP,Poole,0.1,0.08,0.09,0.08,0.12,0.14,0.13,0.13,0.16,0.21,0.1
29,E06000030,00HX,Swindon,0.12,0.09,0.12,0.11,0.08,0.11,0.11,0.11,0.13,0.12,0.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,E10000018,31,Leicestershire,-,-,-,-,-,-,-,-,-,-,-
139,E10000019,32,Lincolnshire,0.14,0.11,0.12,0.09,0.12,0.08,0.1,0.1,0.13,0.1,0.14
140,E10000020,33,Norfolk,0.1,0.12,0.16,0.14,0.1,0.14,0.15,0.13,0.13,0.11,0.1
141,E10000021,34,Northamptonshire,-,-,-,-,-,-,-,-,-,-,-
142,E10000023,36,North Yorkshire,0.09,0.07,0.09,0.1,0.11,0.08,0.1,0.11,0.1,0.09,0.09
143,E10000024,37,Nottinghamshire,-,-,-,-,-,-,-,-,-,-,-
144,E10000025,38,Oxfordshire,0.07,0.12,0.05,0.07,0.09,0.09,0.06,0.09,0.04,0.1,0.07
145,E10000027,40,Somerset,0.1,0.06,0.07,0.12,0.13,0.07,0.1,0.12,0.14,0.11,0.1
146,E10000028,41,Staffordshire,0.13,0.09,0.1,0.08,0.11,0.15,0.12,0.12,0.1,0.09,0.13
147,E10000029,42,Suffolk,0.12,0.09,0.08,0.09,0.09,0.11,0.12,0.12,0.14,0.11,0.12
148,E10000030,43,Surrey,0.05,0.06,0.07,0.07,0.08,0.09,0.1,0.09,0.07,0.06,0.05
149,E10000031,44,Warwickshire,0.1,0.07,0.09,0.07,0.08,0.1,0.15,0.12,0.15,0.11,0.1
150,E10000032,45,West Sussex,0.09,0.08,0.11,0.09,0.08,0.1,0.14,0.09,0.08,0.07,0.09
151,E10000034,47,Worcestershire,0.1,0.09,0.1,0.1,0.14,0.09,0.11,0.07,0.08,0.08,0.1
152,E12000001,NaN,North East,0.18,0.19,0.18,0.2,0.18,0.19,0.21,0.2,0.21,0.2,0.18
153,E12000002,NaN,North West,0.18,0.17,0.18,0.17,0.18,0.19,0.19,0.18,0.19,0.18,0.18
154,E12000003,NaN,Yorkshire and the Humber,0.16,0.17,0.16,0.17,0.16,0.16,0.18,0.19,0.18,0.17,0.16
155,E12000004,NaN,East Midlands,0.12,0.13,0.14,0.13,0.12,0.13,0.15,0.16,0.16,0.13,0.12
156,E12000005,NaN,West Midlands,0.18,0.16,0.16,0.21,0.23,0.25,0.2,0.2,0.23,0.22,0.18
157,E12000006,NaN,East of England,0.1,0.11,0.11,0.11,0.12,0.12,0.12,0.12,0.12,0.12,0.1
158,E12000007,NaN,London,0.17,0.25,0.24,0.25,0.23,0.23,0.22,0.22,0.2,0.18,0.17
159,E12000008,NaN,South East,0.09,0.1,0.1,0.1,0.1,0.11,0.11,0.11,0.1,0.11,0.09
160,E12000009,NaN,South West,0.1,0.11,0.1,0.11,0.11,0.12,0.12,0.12,0.11,0.11,0.1
161,E92000001,NaN,England,0.14,0.15,0.15,0.16,0.15,0.16,0.16,0.16,0.16,0.15,0.14
162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163,1 Households including at least one person age...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,2 A workless household is a household that co...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,3 Children refers to all children under 16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,- Data is not available or has been combined w...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN